apiVersion: rbac.enterprise.mesh.gloo.solo.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: gloo-mesh-enterprise
    meta.helm.sh/release-namespace: gloo-mesh
  labels:
    app: gloo-mesh
    app.kubernetes.io/managed-by: Helm
  name: admin-role-binding
  namespace: gloo-mesh
spec:
  roleRef:
    name: admin-role
    namespace: gloo-mesh
  subjects:
  - kind: Group
    name: system:masters
  - kind: User
    name: system:serviceaccount:argocd:argocd-application-controller
